name: hiklik_sports
description: A new Flutter project.

publish_to: "none"

version: 0.1.1+8

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.13
  firebase_core: ^2.1.1
  page_transition: ^2.0.9
  dropdown_button2: ^1.8.9
  firebase_auth: ^4.1.0
  intl: ^0.17.0
  cloud_firestore: ^4.0.3
  http: ^0.13.5
  url_launcher: ^6.1.6
  flutter_slidable: ^2.0.0
  awesome_dialog: ^3.0.2
  cached_network_image: ^3.2.2
  flutter_html: ^3.0.0-alpha.6
  expandable: ^5.0.1
  image_picker: ^0.8.6
  firebase_storage: ^11.0.3
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  image_cropper: ^3.0.1
  pull_to_refresh: ^2.0.0
  google_sign_in: ^5.4.2
  crypto: ^3.0.2
  flutter_widget_from_html: ^0.9.0+1
  ntp: ^2.0.0
  webview_flutter: ^2.8.0
  flutter_inapp_purchase: ^5.3.1
  flutter_inappwebview: ^5.7.1+2
  video_player: ^2.4.7
  chewie: ^1.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
