// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv2sxJVWsM_-BNzwtCjGCqiApKufcK7SE',
    appId: '1:80054763997:web:d4fe3dc4f54ce6b830f634',
    messagingSenderId: '80054763997',
    projectId: 'hiklik-isoc',
    authDomain: 'hiklik-isoc.firebaseapp.com',
    storageBucket: 'hiklik-isoc.appspot.com',
    measurementId: 'G-MTDP3NL42D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtd8iaWVzIzg79MKm8rWsunYa81Src4J8',
    appId: '1:80054763997:android:8b1bb16c48f03e3d30f634',
    messagingSenderId: '80054763997',
    projectId: 'hiklik-isoc',
    storageBucket: 'hiklik-isoc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAMTojF-5HDuIM-hXREuc0inIKEJuS2Xc',
    appId: '1:80054763997:ios:a1dfa69350b876d430f634',
    messagingSenderId: '80054763997',
    projectId: 'hiklik-isoc',
    storageBucket: 'hiklik-isoc.appspot.com',
    iosClientId: '80054763997-33pn89e6qku1vqovtjrfhcbnn2vf1sav.apps.googleusercontent.com',
    iosBundleId: 'com.hiklik.isoc',
  );
}
